# Generated by Django 6.1 on 2026-08-22 16:12

import booking_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ماركة السيارة')),
                ('icon_name', models.CharField(blank=True, default='car', max_length=50, verbose_name='رمز الماركة')),
            ],
            options={
                'verbose_name': 'ماركة سيارة',
                'verbose_name_plural': 'ماركات السيارات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (ج.م)')),
                ('duration_mins', models.IntegerField(default=45, verbose_name='المدة بالدقائق')),
                ('icon_type', models.CharField(default='wrench', max_length=50, verbose_name='أيقونة الخدمة')),
                ('is_popular', models.BooleanField(default=False, verbose_name='الأكثر طلباً')),
                ('included_features', models.TextField(help_text='مثال: فحص الزيوت, قياس ضغط الإطارات, تقرير فوتوغرافي', verbose_name='المميزات المشمولة (مفصولة بفارزة)')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time_label', models.CharField(max_length=50, verbose_name='الوقت')),
                ('period', models.CharField(choices=[('morning', 'صباحاً (09:00 - 12:00)'), ('afternoon', 'ظهراً (12:00 - 04:00)'), ('evening', 'مساءً (04:00 - 08:00)')], default='morning', max_length=20, verbose_name='الفترة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
            ],
            options={
                'verbose_name': 'موعد صيانة',
                'verbose_name_plural': 'مواعيد الصيانة',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='موديل السيارة')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='booking_app.carmake', verbose_name='الماركة')),
            ],
            options={
                'verbose_name': 'موديل سيارة',
                'verbose_name_plural': 'موديلات السيارات',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(default=booking_app.models.generate_ticket_code, max_length=30, unique=True, verbose_name='رقم أمر العمل')),
                ('customer_name', models.CharField(max_length=150, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('district', models.CharField(choices=[('October', 'مدينة 6 أكتوبر'), ('Zayed', 'الشيخ زايد')], default='October', max_length=50, verbose_name='المنطقة')),
                ('address_notes', models.TextField(blank=True, verbose_name='ملاحظات العنوان / الموقع')),
                ('car_make', models.CharField(max_length=100, verbose_name='ماركة السيارة')),
                ('car_model', models.CharField(max_length=100, verbose_name='موديل السيارة')),
                ('car_year', models.IntegerField(verbose_name='سنة الصنع')),
                ('plate_number', models.CharField(blank=True, max_length=50, verbose_name='رقم اللوحة')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('booking_time', models.CharField(max_length=50, verbose_name='وقت الحجز')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي (ج.م)')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('in_progress', 'قيد الصيانة'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='confirmed', max_length=20, verbose_name='حالة أمر العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_app.service', verbose_name='الخدمة المختارة')),
            ],
            options={
                'verbose_name': 'حجز صيانة',
                'verbose_name_plural': 'حجوزات الصيانة',
            },
        ),
    ]
