# Generated by Django 6.1 on 2026-08-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('maintenance', 'صيانة دورية'), ('brakes', 'فرامل وسلامة'), ('ac', 'تكييف وتبريد'), ('scan', 'كشف كمبيوتر'), ('engine', 'محرك وزيوت')], default='maintenance', max_length=50, verbose_name='قسم الخدمة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='الأكثر طلباً / الأكثر مبيعاً'),
        ),
    ]
