# Generated by Django 6.1 on 2026-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_service_category_alter_service_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='district',
            field=models.CharField(choices=[('October', 'مدينة 6 أكتوبر'), ('Zayed', 'الشيخ زايد'), ('Haram_Gardens', 'حدائق الأهرام'), ('October_Gardens', 'حدائق أكتوبر'), ('New_Cairo', 'التجمع والقاهرة الجديدة'), ('Maadi', 'المعادي'), ('Other', 'منطقة أخرى')], default='October', max_length=50, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'تم تأكيد الحجز 🟢'), ('on_the_way', 'سيارة الصيانة في الطريق 🚚'), ('in_progress', 'جاري الصيانة بموقعك ⚙️'), ('completed', 'اكتملت الصيانة بنجاح ✅'), ('cancelled', 'تم الإلغاء ❌')], default='confirmed', max_length=20, verbose_name='حالة أمر العمل'),
        ),
    ]
