# Generated by Django 5.2.17 on 2026-08-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الماركة')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='أيقونة')),
            ],
            options={
                'verbose_name': 'ماركة',
                'verbose_name_plural': 'الماركات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_mins', models.IntegerField(default=45, verbose_name='المدة بالدقايق')),
                ('icon_type', models.CharField(default='wrench', max_length=50, verbose_name='نوع الأيقونة')),
                ('is_popular', models.BooleanField(default=False, verbose_name='الأكثر طلباً')),
                ('included_features', models.TextField(blank=True, help_text='افصل كل بند بسطر جديد', verbose_name='اللي شامله')),
                ('category', models.CharField(choices=[('maintenance', 'صيانة دورية'), ('engine', 'المحرك والزيوت'), ('brakes', 'الفرامل والسلامة'), ('ac', 'التكييف والتبريد'), ('scan', 'فحص وتشخيص'), ('electric', 'كهرباء وبطارية'), ('care', 'عناية ونظافة')], default='maintenance', max_length=50, verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['-is_popular', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time_label', models.CharField(max_length=50, verbose_name='الميعاد')),
                ('period', models.CharField(choices=[('morning', 'صباحاً'), ('afternoon', 'بعد الضهر'), ('evening', 'بالليل')], max_length=20, verbose_name='الفترة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
            ],
            options={
                'verbose_name': 'ميعاد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الموديل')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='booking_app.carmake', verbose_name='الماركة')),
            ],
            options={
                'verbose_name': 'موديل',
                'verbose_name_plural': 'الموديلات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم الحجز')),
                ('customer_name', models.CharField(max_length=150, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='الموبايل')),
                ('district', models.CharField(choices=[('zayed_3', 'الشيخ زايد — الحي الثالث'), ('zayed_16', 'الشيخ زايد — الحي السادس عشر'), ('beverly', 'بيفرلي هيلز'), ('arkan', 'أركان'), ('zayed_2000', 'زايد 2000'), ('dreamland', 'دريم لاند'), ('gardenia', 'جاردينيا هايتس'), ('oct_1', 'أكتوبر — الحي الأول'), ('oct_7', 'أكتوبر — الحي السابع'), ('oct_12', 'أكتوبر — الحي الثاني عشر'), ('palm', 'بالم هيلز أكتوبر'), ('othman', 'مساكن عثمان'), ('hadayek', 'حدائق أكتوبر')], max_length=50, verbose_name='المنطقة')),
                ('address_notes', models.TextField(verbose_name='تفاصيل العنوان')),
                ('car_make', models.CharField(max_length=100, verbose_name='الماركة')),
                ('car_model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('car_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('plate_number', models.CharField(blank=True, max_length=50, verbose_name='رقم اللوحة')),
                ('booking_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('booking_time', models.CharField(max_length=50, verbose_name='ميعاد الزيارة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'في انتظار التأكيد'), ('confirmed', 'مؤكد'), ('done', 'تم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='اتعمل في')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_app.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
